version: '2'
services:
  website:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php73
    image: php:7.3-apache
    depends_on:
      - db
    volumes:
      - ./php:/var/www/html
    ports:
      - 4000:80
  db:
    container_name: mysql8
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports: 
      - 6033:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - 4040:80
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: front
    volumes:
      - ./front:/var/www/html
    ports:
      - 4080:80